Полная разметка главной страницы
prikhodkin/sedona pull request #2
Opened 2023-08-28 20:58 UTC by alex21072

2023-08-29 05:33 UTC, prikhodkin commented on index.html
> +      <a href="#"><img src="#" height="100" width="100" alt="Логотип"></a>
Please move img tag on the next line

2023-08-29 05:33 UTC, prikhodkin commented on index.html
> +        <a href="#"><img src="#" width="18" height="18" alt="Поиск"></a>
Please move img tag on the next line

2023-08-29 05:33 UTC, prikhodkin commented on index.html
> +        <a href="#"><img src="#" width="18" height="18" alt="Избранное"></a>
Please move img tag on the next line

2023-08-29 05:33 UTC, prikhodkin commented on index.html
> +        <h1>Седона — небольшой городок в Аризоне,<br>заслуживающий большего!</h1>
Don't use br tag

2023-08-29 05:35 UTC, prikhodkin commented on index.html
> +        <img src="#" width="457" height="213" alt="SEDONA becouse the grand canyon sucks!">
Please merge 3 pictures into 1

2023-08-29 05:38 UTC, prikhodkin commented on index.html
> +      </section>
Not valid code. Please check the nesting of tags. ( ul > li )

2023-08-29 05:40 UTC, prikhodkin commented on index.html
> +          <a href="#"><img src="#" width="70" height="30" alt="Twitter"></a>
Please move img tag on the next line

2023-08-29 05:40 UTC, prikhodkin commented on index.html
> +          <a href="#"><img src="#" width="70" height="30" alt="Facebook"></a>
Please move img tag on the next line

2023-08-29 05:40 UTC, prikhodkin commented on index.html
> +          <a href="#"><img src="#" width="70" height="30" alt="YOutube"></a>
Please move img tag on the next line

2023-08-29 05:40 UTC, prikhodkin commented on index.html
> +      <a href="#"><img src="#" width="115" height="34" alt="Логотип HTML"></a>
Please move img tag on the next line

2023-08-29 05:42 UTC, prikhodkin commented on index.html
> +      <div class=phone><a href="tel:+78128121212">+7 (812) 812-12-12</a>
div is redundant. Use just <a href="tel:+78128121212">+7 (812) 812-12-12</a>

2023-08-29 05:42 UTC, prikhodkin requested changes
Please check issues

2023-08-29 19:40 UTC, alex21072 commented
corrected all the comments

2023-08-31 17:02 UTC, prikhodkin approved these changes

2023-08-31 17:02 UTC, merged